<?php

/**
 * Implements hook_help()
 */
function press_esc_to_login_help($path, $arg) {
  switch ($path) {
    case 'admin/help#press_esc_to_login':
      return t('Press the escape key (ESC) from any page to quickly navigate to the admin login page.');
  }
}

/**
 * Implements hook_page_build().
 */
function press_esc_to_login_page_build(&$page) {
  global $base_url;

  $path_to_js = drupal_get_path('module', 'press_esc_to_login'). '/press_esc_to_login.js';

  if (!user_is_logged_in()) {
    drupal_add_js($path_to_js);
    drupal_add_js(['pressEscToLogin' => ['loginPath' => $base_url . '/user']], 'setting');
  }
}
